import { useState } from "react";
import { Plus, Upload, X } from "lucide-react";
import type { MoneySettings, Transaction } from "@orchestrator/contracts";
import { Dialog } from "./alpha-pages.js";
import { api } from "./lib.js";
import { PersonalAdvice, PersonalCard, PersonalMeter, type PersonalAction, type PersonalPanelProps } from "./personal-page.js";

const cash = (minor: number, currency: string) => new Intl.NumberFormat("en", { style: "currency", currency }).format(minor / 100);
const schemas = {
  transactions: "id,date,description,amount,type,category,currency",
  holdings: "id,name,assetClass,value,currency,asOf",
  calendar: "id,title,date,time,minutes,note",
};
export function ImportPersonal({ kind, act, busy, close }: { kind: keyof typeof schemas; act: PersonalAction; busy: boolean; close(): void }) {
  const [csv, setCsv] = useState(schemas[kind] + "\n"), [source, setSource] = useState(""), [error, setError] = useState(""), [loading, setLoading] = useState(false);
  const [preview, setPreview] = useState<{ id: string; added: number; updated: number; duplicate: number; count: number; rows: Array<Record<string, unknown>> } | null>(null);
  async function inspect(e: React.FormEvent) { e.preventDefault(); setLoading(true); setError(""); try { setPreview(await api("/api/personal/import/preview", { method: "POST", body: JSON.stringify({ kind, source, csv }) })); } catch (e) { setError(e instanceof Error ? e.message : "Could not preview file"); } finally { setLoading(false); } }
  return <Dialog title={`Import ${kind}`} close={close}><form className="alpha-form" onSubmit={inspect}><p className="form-note">{kind === "calendar" ? "Import one row per commitment. Times are local wall-clock times; this is a snapshot, with no live calendar sync or recurrence expansion." : "Records stay encrypted on this gateway. This import makes no bank, broker or model connection."} Reuse the same source name and stable row ids to avoid duplicates.</p><label>Source name<input value={source} required maxLength={100} placeholder={kind === "calendar" ? "My calendar export" : "My current account"} onChange={(e) => { setSource(e.target.value); setPreview(null); }} /></label><label>CSV file<input type="file" accept=".csv,text/csv" onChange={async (e) => { const file = e.target.files?.[0]; if (!file) return; if (file.size > 200000) { setError("Use a CSV under 200 KB, with up to 1,000 rows."); return; } setCsv(await file.text()); setPreview(null); }} /></label><details><summary>Columns and formatting</summary><p className="form-note"><code>{schemas[kind]}</code></p><p className="form-note">Dates: YYYY-MM-DD. {kind === "transactions" ? "Positive amounts use a dot decimal separator. Type: income, expense, refund or transfer. Refunds offset spending in their category; transfers do not count as income or expenses." : kind === "holdings" ? "Value is the total position value, using a dot decimal separator. A newer asOf date replaces the same holding id; older or conflicting snapshots are rejected." : "Time: HH:MM or empty for an all-day item. Minutes: 5–1440. Every row needs a unique id."} {kind !== "calendar" && "Currencies: EUR, USD, GBP or CHF. No currency conversion is performed."}</p></details><label>CSV contents<textarea required rows={6} maxLength={200000} value={csv} spellCheck={false} onChange={(e) => { setCsv(e.target.value); setPreview(null); }} /></label>{error && <p role="alert" className="form-error">{error}</p>}{!preview && <button className="button button--primary" disabled={loading || busy}>Preview import</button>}</form>
    {preview && <div className="personal-detail"><h3>{preview.added} new · {preview.updated} updated · {preview.duplicate} unchanged</h3><p className="form-note">{preview.count} rows validated. First {preview.rows.length} shown below. Nothing is imported until you save.</p><div className="personal-table-wrap"><table className="personal-table"><thead><tr><th>Record</th><th>Details</th></tr></thead><tbody>{preview.rows.map((r) => <tr key={String(r.id)}><td>{String(r.description ?? r.name ?? r.title)}</td><td>{kind === "calendar" ? `${r.date} ${r.time ?? "All day"}` : `${r.date ?? r.asOf} · ${cash(Number(r.amount ?? r.value), String(r.currency))}`}</td></tr>)}</tbody></table></div><button className="button button--primary" disabled={busy} onClick={async () => { if (await act(`/api/personal/import/${preview.id}/commit`)) close(); }}>Save {preview.count} records</button></div>}
  </Dialog>;
}

export function MoneyPanel({ data, act, busy, changeMonth }: PersonalPanelProps & { changeMonth(month: string): void }) {
  const [importing, setImporting] = useState<"transactions" | "holdings" | null>(null), [editing, setEditing] = useState(false), [transaction, setTransaction] = useState<Transaction | null>(null);
  const m = data.money;
  const [removeSource, setRemoveSource] = useState("");
  return <><div className="personal-toolbar"><p><input className="personal-month" aria-label="Statement month" type="month" value={m.month} max={data.today.slice(0, 7)} onChange={(e) => { if (e.target.value) changeMonth(e.target.value); }} /> · {m.currency}</p><div className="personal-shortcuts"><button className="button button--secondary" onClick={() => setEditing(true)}>My money plan</button><button className="button button--primary" onClick={() => setImporting("transactions")}><Upload size={16} /> Import statement</button></div></div>
    <div className="personal-grid"><PersonalCard title="Monthly cash flow" detail={m.latestTransaction ? `Latest transaction: ${m.latestTransaction}` : "Import a statement to see where your money goes."}><p className="money-big">{cash(m.net, m.currency)}</p><p className="form-note">Net recorded income less spending · not your account balance</p><div className="money-subtotals"><div>Income<strong>{cash(m.income, m.currency)}</strong></div><div>Spending, less refunds<strong>{cash(m.spent, m.currency)}</strong></div></div>{!!m.excluded && <p className="form-note">{m.excluded} records in other currencies are excluded. Switch currency in My money plan.</p>}{m.categories.map((c) => <div className="money-category" key={c.category}><div><span>{c.category}</span><span>{cash(c.spent, m.currency)}{c.limit !== null ? ` / ${cash(c.limit, m.currency)}` : ""}</span></div><PersonalMeter label={`${c.category} budget usage`} value={c.spent} max={c.limit ?? Math.max(m.spent, 1)} /><small>{c.limit === null ? "No limit set" : c.spent > c.limit ? `${cash(c.spent - c.limit, m.currency)} over your limit` : `${cash(c.limit - c.spent, m.currency)} left in your plan`}</small></div>)}</PersonalCard>
      <PersonalCard title="Your portfolio" detail={m.oldestHolding ? `Oldest valuation: ${m.oldestHolding} · No live prices` : "Start with your objective, then import a holdings snapshot."} action={<button className="icon-button" aria-label="Import holdings" onClick={() => setImporting("holdings")}><Plus size={18} /></button>}><p className="money-big">{cash(m.total, m.currency)}</p>{m.allocation.map((a) => <div className="money-category" key={a.assetClass}><div><span>{a.assetClass}</span><span>{a.percent.toFixed(1)}%</span></div><PersonalMeter label={`${a.assetClass} allocation`} value={a.percent} max={100} /><small>{cash(a.value, m.currency)}{a.target === null ? " · No target set" : ` · Target ${a.target}%${a.drift === null ? "" : ` · Drift ${a.drift > 0 ? "+" : ""}${a.drift.toFixed(1)} pp`}`}</small></div>)}<p className="form-note">{data.settings.objective || "Set your investing objective, time horizon and comfort with losses in My money plan."}</p>{(!data.settings.horizon || data.settings.risk === "unset") && <p className="form-note">Your investing profile is incomplete. Allocation targets are your inputs; the app does not infer suitability.</p>}<PersonalAdvice area="money" /><p /><a className="personal-inline-link" href="https://www.investor.gov/introduction-investing" target="_blank" rel="noreferrer">Understand the investing basics ↗</a></PersonalCard></div>
    <div style={{ marginTop: 20 }}><PersonalCard title="Transaction record" detail="Select a transaction to correct its category or type. Latest 100 shown."><div className="personal-table-wrap"><table className="personal-table"><thead><tr><th>Date / source</th><th>Description</th><th>Category</th><th>Amount</th></tr></thead><tbody>{[...data.transactions].sort((a, b) => b.date.localeCompare(a.date)).slice(0, 100).map((t) => <tr key={t.id}><td>{t.date}<br /><small>{t.source}</small></td><td><button className="button button--ghost" onClick={() => setTransaction(t)}>{t.description}</button></td><td>{t.category}<br /><small>{t.type}</small></td><td>{cash(t.amount, t.currency)}</td></tr>)}</tbody></table>{!data.transactions.length && <p className="form-note">No financial records yet. Your first import can contain a complete month, so we can prepare a budget baseline.</p>}</div></PersonalCard></div>
    {!!data.holdings.length && <details className="personal-detail"><summary>Inspect individual holdings and sources</summary><div className="personal-table-wrap"><table className="personal-table"><thead><tr><th>Holding / source</th><th>Class</th><th>As of</th><th>Value</th></tr></thead><tbody>{data.holdings.map((h) => <tr key={h.id}><td>{h.name}<br /><small>{h.source}</small></td><td>{h.assetClass}</td><td>{h.asOf}</td><td>{cash(h.value, h.currency)}</td></tr>)}</tbody></table></div></details>}
    <details className="personal-detail"><summary>Export or correct an imported source</summary><p className="form-note">The export contains your personal records as readable JSON. Keep it somewhere private.</p><a href="/api/personal/export" download className="button button--secondary">Export personal records</a><form className="alpha-form" onSubmit={async (e) => { e.preventDefault(); const form = e.currentTarget; const [kind, source] = JSON.parse(removeSource) as [string, string]; if (await act("/api/personal/imported-source", { kind, source, confirmed: true }, "DELETE")) { setRemoveSource(""); form.reset(); } }}><label>Imported source<select value={removeSource} required onChange={(e) => setRemoveSource(e.target.value)}><option value="">Choose a source to remove</option>{(["transactions", "holdings"] as const).flatMap((kind) => [...new Set(data[kind].map((r) => r.source))].map((source) => <option key={`${kind}-${source}`} value={JSON.stringify([kind, source])}>{source} · {kind}</option>))}</select></label><label className="check-label"><input type="checkbox" required /><span>Remove all records of this type from the selected source and reset its import history. Other sources and my money plan remain.</span></label><button className="button button--secondary" disabled={busy || !removeSource}>Remove imported records</button></form></details>
    {importing && <ImportPersonal kind={importing} act={act} busy={busy} close={() => setImporting(null)} />}{editing && <MoneyPlan settings={data.settings} act={act} busy={busy} close={() => setEditing(false)} />}
    {transaction && <Dialog title="Correct transaction" close={() => setTransaction(null)}><form className="alpha-form" onSubmit={async (e) => { e.preventDefault(); const f = new FormData(e.currentTarget); if (await act(`/api/personal/transactions/${transaction.id}`, { category: f.get("category"), type: f.get("type") }, "PATCH")) setTransaction(null); }}><p>{transaction.description} · {cash(transaction.amount, transaction.currency)}</p><label>Category<input name="category" required maxLength={80} defaultValue={transaction.category} /></label><label>Type<select name="type" defaultValue={transaction.type}>{["income", "expense", "refund", "transfer"].map((t) => <option key={t}>{t}</option>)}</select></label><button className="button button--primary" disabled={busy}>Save correction</button></form></Dialog>}
  </>;
}

function MoneyPlan({ settings, act, busy, close }: { settings: MoneySettings; act: PersonalAction; busy: boolean; close(): void }) {
  const [value, setValue] = useState(settings), [baseline, setBaseline] = useState<{ month: string; currency: string; limits: MoneySettings["limits"]; note: string } | null>(null), [error, setError] = useState("");
  return <Dialog title="My money plan" close={close}><form className="alpha-form" onSubmit={async (e) => { e.preventDefault(); if (await act("/api/personal/money/settings", value, "PUT")) close(); }}><label>Currency<select value={value.currency} onChange={(e) => { setValue({ ...value, currency: e.target.value as MoneySettings["currency"], limits: [], targets: [] }); setBaseline(null); }}>{["EUR", "USD", "GBP", "CHF"].map((c) => <option key={c}>{c}</option>)}</select></label><p className="form-note">Changing currency clears the limits and targets in this draft. Imported records are retained in their original currencies.</p><h3>Monthly limits</h3><button type="button" className="button button--secondary" onClick={async () => { try { const result = await api<{ month: string; currency: string; limits: MoneySettings["limits"]; note: string }>("/api/personal/money/baseline"); if (result.currency !== value.currency) { setError("Save the selected currency before preparing its baseline."); return; } setBaseline(result); setError(""); } catch { setError("Could not prepare baseline. Try again."); } }}>Prepare from last month</button>{baseline && <div className="personal-detail"><p className="form-note">{baseline.month}: {baseline.note}</p>{baseline.limits.length ? <><ul>{baseline.limits.map((l) => <li key={l.category}>{l.category}: {cash(l.amount, baseline.currency)}</li>)}</ul><button type="button" className="button button--secondary" onClick={() => { setValue({ ...value, limits: baseline.limits }); setBaseline(null); }}>Use these limits</button></> : <p className="form-note">No spending recorded for that month. Import the statement first, or set your own limits below.</p>}</div>}{error && <p className="form-error" role="alert">{error}</p>}
    {value.limits.map((l, i) => <div className="personal-form-grid" key={i}><label>Category {i + 1}<input required maxLength={80} value={l.category} onChange={(e) => setValue({ ...value, limits: value.limits.map((r, n) => n === i ? { ...r, category: e.target.value } : r) })} /></label><label>Monthly amount ({value.currency})<span className="personal-shortcuts"><input type="number" min="0" step="0.01" required value={l.amount / 100} onChange={(e) => setValue({ ...value, limits: value.limits.map((r, n) => n === i ? { ...r, amount: Math.round(Number(e.target.value) * 100) } : r) })} /><button type="button" className="icon-button" aria-label={`Remove limit ${i + 1}`} onClick={() => setValue({ ...value, limits: value.limits.filter((_, n) => n !== i) })}><X size={16} /></button></span></label></div>)}<button type="button" className="button button--ghost" onClick={() => setValue({ ...value, limits: [...value.limits, { category: "", amount: 0 }] })}><Plus size={15} /> Add category</button>
    <h3>Investing intentions</h3><label>What is this money for?<textarea rows={2} maxLength={1000} value={value.objective} onChange={(e) => setValue({ ...value, objective: e.target.value })} /></label><label>When might you need it?<input maxLength={200} placeholder="For example, not for at least ten years" value={value.horizon} onChange={(e) => setValue({ ...value, horizon: e.target.value })} /></label><label>Comfort with investment losses<select value={value.risk} onChange={(e) => setValue({ ...value, risk: e.target.value as MoneySettings["risk"] })}><option value="unset">Still exploring</option><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label><details><summary>Allocation targets (optional)</summary><p className="form-note">Enter targets you have chosen. They must total 100%. Drift compares imported values with these targets; it is not a trade recommendation.</p>{value.targets.map((t, i) => <div className="personal-form-grid" key={i}><label>Asset class {i + 1}<input required value={t.assetClass} maxLength={80} onChange={(e) => setValue({ ...value, targets: value.targets.map((r, n) => n === i ? { ...r, assetClass: e.target.value } : r) })} /></label><label>Target percent<span className="personal-shortcuts"><input type="number" required min={0} max={100} step="0.1" value={t.percent} onChange={(e) => setValue({ ...value, targets: value.targets.map((r, n) => n === i ? { ...r, percent: Number(e.target.value) } : r) })} /><button type="button" className="icon-button" aria-label={`Remove target ${i + 1}`} onClick={() => setValue({ ...value, targets: value.targets.filter((_, n) => n !== i) })}><X size={16} /></button></span></label></div>)}<button type="button" className="button button--ghost" onClick={() => setValue({ ...value, targets: [...value.targets, { assetClass: "", percent: 0 }] })}><Plus size={15} /> Add target</button></details><button className="button button--primary" disabled={busy}>Save money plan</button></form></Dialog>;
}
