import { useState } from "react";
import { Check, Download, Plus, Upload } from "lucide-react";
import type { Commitment, PersonalGoal } from "@orchestrator/contracts";
import { Dialog } from "./alpha-pages.js";
import { AssistantSigil } from "./presence.js";
import { ImportPersonal } from "./personal-money.js";
import { PersonalAdvice, PersonalCard, PersonalMeter, type PersonalPanelProps } from "./personal-page.js";

export function LifePanel({ data, act, busy }: PersonalPanelProps) {
  const [goal, setGoal] = useState<PersonalGoal | "new" | null>(null), [checkin, setCheckin] = useState<string | null>(null), [commitment, setCommitment] = useState<Commitment | "new" | null>(null), [importing, setImporting] = useState(false), [showDone, setShowDone] = useState(false);
  const [checkinRequest, setCheckinRequest] = useState(() => crypto.randomUUID());
  const currentGoal = data.goals.find((g) => g.id === checkin), goals = data.goals.filter((g) => !g.archived), agenda = data.commitments.filter((c) => showDone || !c.done).sort((a, b) => `${a.date}${a.time ?? ""}`.localeCompare(`${b.date}${b.time ?? ""}`));
  const editCommitment = (c: Commitment, done: boolean) => ({ title: c.title, date: c.date, time: c.time, minutes: c.minutes, goalId: c.goalId, note: c.note, version: c.version, done });
  return <><div className="personal-toolbar"><p>Keep promises to yourself as visible as promises to others.</p><div className="personal-shortcuts"><button className="button button--secondary" onClick={() => setGoal("new")}>New goal</button><button className="button button--primary" onClick={() => setCommitment("new")}><Plus size={16} /> Add commitment</button></div></div>
    <div className="personal-grid"><PersonalCard title="Your agenda" detail="Dates use UTC today; appointment times are local wall-clock times." action={<button className="icon-button" aria-label="Import calendar" onClick={() => setImporting(true)}><Upload size={17} /></button>}>
      {data.signals.filter((s) => s.id.startsWith("conflict-")).map((s) => <p className="form-error" key={s.id}>{s.detail}</p>)}
      {agenda.slice(0, 100).map((c) => <div className="personal-agenda-row" key={c.id}><button onClick={() => setCommitment(c)}><strong style={{ textDecoration: c.done ? "line-through" : undefined }}>{c.title}</strong><small>{c.date < data.today && !c.done ? "Overdue · " : ""}{c.date === data.today ? "Today" : c.date} · {c.time ?? "All day"} · {c.minutes} min{c.goalId ? ` · ${data.goals.find((g) => g.id === c.goalId)?.title ?? "Archived goal"}` : ""}</small></button><button className="icon-button" aria-label={`${c.done ? "Reopen" : "Complete"} ${c.title}`} disabled={busy} onClick={() => void act(`/api/personal/commitments/${c.id}`, editCommitment(c, !c.done), "PUT")}><Check size={17} /></button></div>)}{!agenda.length && <div className="personal-empty"><h3>A clear day starts here.</h3><p>Capture a commitment or import your calendar. Overdue items and overlapping times appear automatically.</p></div>}<div className="personal-shortcuts" style={{ marginTop: 16 }}><label className="form-note"><input type="checkbox" checked={showDone} onChange={(e) => setShowDone(e.target.checked)} /> Show completed</label><a href="/api/personal/calendar.ics" className="button button--ghost" download><Download size={15} /> Export calendar</a></div><p className="form-note">Export contains open commitments. Importing into a calendar does not send invitations.</p><PersonalAdvice area="agenda" />
    </PersonalCard><PersonalCard title="Goals with a next step" detail="Small, measurable progress. Your pace is yours.">
      <PersonalAdvice area="coach" />
      {!goals.length && <div className="personal-empty"><AssistantSigil name="Coach" icon={3} state="ready" /><h3>Choose one thing worth making time for.</h3><p>Define a measure and a weekly intention. Check-ins build your progress history.</p><button className="button button--secondary" onClick={() => setGoal("new")}>Set my first goal</button></div>}
      {goals.map((g) => { const total = g.checkins.reduce((s, c) => s + c.value, 0), recent = g.checkins.filter((c) => Date.parse(c.date) >= Date.parse(data.today) - 6 * 86400000).reduce((s, c) => s + c.value, 0); return <div className="money-category" key={g.id}><div><button className="button button--ghost" onClick={() => setGoal(g)}>{g.title}</button><span>{total}/{g.target}</span></div><PersonalMeter label={`${g.title} progress`} value={total} max={g.target} /><small>{g.unit} · {recent}/{g.weekly} in the last seven days{g.due ? ` · Due ${g.due}` : ""}</small><p className="form-note">{total >= g.target ? "You reached the target you set. Take a moment to reflect on what helped." : recent >= g.weekly ? "You met your weekly intention. Keep the pace sustainable." : recent === 0 ? "No progress recorded this week. Make the next step small enough to start." : "Progress is building. Reserve time for the next manageable step."}</p><div className="personal-shortcuts"><button className="button button--secondary" onClick={() => { setCheckinRequest(crypto.randomUUID()); setCheckin(g.id); }}>Check in</button><button className="button button--ghost" onClick={() => setCommitment({ title: `Make time for ${g.title}`, date: data.today, time: null, minutes: 30, goalId: g.id, note: g.why, id: "", version: 1, done: false, source: "Manual", createdAt: "" })}>Make time</button></div></div>; })}
      {data.goals.some((g) => g.archived) && <details><summary>Archived goals</summary>{data.goals.filter((g) => g.archived).map((g) => <button className="button button--ghost" key={g.id} onClick={() => setGoal(g)}>{g.title}</button>)}</details>}
    </PersonalCard></div>
    {goal && <Dialog title={goal === "new" ? "A goal that matters to you" : "Adjust your goal"} close={() => setGoal(null)}><form className="alpha-form" onSubmit={async (e) => { e.preventDefault(); const f = new FormData(e.currentTarget), body = { title: f.get("title"), why: f.get("why"), target: Number(f.get("target")), unit: f.get("unit"), weekly: Number(f.get("weekly")), due: f.get("due") || null, ...(goal === "new" ? {} : { version: goal.version, archived: f.get("archived") === "on" }) }; if (await act(goal === "new" ? "/api/personal/goals" : `/api/personal/goals/${goal.id}`, body, goal === "new" ? "POST" : "PATCH")) setGoal(null); }}><label>Goal<input name="title" required maxLength={120} defaultValue={goal === "new" ? "" : goal.title} placeholder="Make time for focused work" /></label><label>Why it matters<textarea name="why" required maxLength={1000} rows={2} defaultValue={goal === "new" ? "" : goal.why} /></label><div className="personal-form-grid"><label>Total target<input name="target" type="number" required min="0.01" step="any" defaultValue={goal === "new" ? 20 : goal.target} /></label><label>Unit<input name="unit" required maxLength={40} defaultValue={goal === "new" ? "sessions" : goal.unit} /></label><label>Weekly intention<input name="weekly" type="number" required min="0.01" step="any" defaultValue={goal === "new" ? 3 : goal.weekly} /></label><label>Target date (optional)<input name="due" type="date" defaultValue={goal === "new" ? "" : goal.due ?? ""} /></label></div>{goal !== "new" && <label className="check-label"><input name="archived" type="checkbox" defaultChecked={goal.archived} /><span>Archive this goal, keeping its history</span></label>}<button className="button button--primary" disabled={busy}>Save goal</button></form></Dialog>}
    {currentGoal && <Dialog title={`Check in: ${currentGoal.title}`} close={() => setCheckin(null)}><form className="alpha-form" onSubmit={async (e) => { e.preventDefault(); const form = e.currentTarget, f = new FormData(form); if (await act(`/api/personal/goals/${currentGoal.id}/checkins`, { id: checkinRequest, date: f.get("date"), value: Number(f.get("value")), note: f.get("note") })) { form.reset(); setCheckinRequest(crypto.randomUUID()); } }}><div className="personal-form-grid"><label>Date<input name="date" type="date" max={data.today} defaultValue={data.today} required /></label><label>Progress ({currentGoal.unit})<input name="value" type="number" min="0.01" max="1000000000" step="any" defaultValue={1} required /></label></div><label>What helped or got in the way?<textarea name="note" rows={2} maxLength={2000} /></label><button className="button button--primary" disabled={busy}>Record progress</button></form><div className="personal-detail"><h3>Your progress history</h3>{[...currentGoal.checkins].reverse().map((c) => <div className="personal-agenda-row" key={c.id}><div style={{ flex: 1 }}><strong>{c.value} {currentGoal.unit} · {c.date}</strong><p className="form-note">{c.note || "No reflection added."}</p></div><button className="button button--ghost" disabled={busy} onClick={() => void act(`/api/personal/goals/${currentGoal.id}/checkins/${c.id}`, undefined, "DELETE")}>Undo</button></div>)}</div></Dialog>}
    {commitment && <Dialog title={commitment === "new" || !commitment.id ? "Make a little room" : "Edit commitment"} close={() => setCommitment(null)}><form className="alpha-form" onSubmit={async (e) => { e.preventDefault(); const f = new FormData(e.currentTarget), existing = commitment !== "new" && !!commitment.id, body = { title: f.get("title"), date: f.get("date"), time: f.get("time") || null, minutes: Number(f.get("minutes")), goalId: f.get("goalId") || null, note: f.get("note"), ...(existing ? { version: commitment.version, done: commitment.done } : {}) }; if (await act(existing ? `/api/personal/commitments/${commitment.id}` : "/api/personal/commitments", body, existing ? "PUT" : "POST")) setCommitment(null); }}><label>Commitment<input name="title" required maxLength={180} defaultValue={commitment === "new" ? "" : commitment.title} /></label><div className="personal-form-grid"><label>Date<input name="date" type="date" required defaultValue={commitment === "new" ? data.today : commitment.date} /></label><label>Time (optional)<input name="time" type="time" defaultValue={commitment === "new" ? "" : commitment.time ?? ""} /></label><label>Minutes<input name="minutes" type="number" min={5} max={1440} required defaultValue={commitment === "new" ? 30 : commitment.minutes} /></label><label>Supports a goal<select name="goalId" defaultValue={commitment === "new" ? "" : commitment.goalId ?? ""}><option value="">No linked goal</option>{data.goals.map((g) => <option key={g.id} value={g.id}>{g.title}{g.archived ? " (archived)" : ""}</option>)}</select></label></div><label>Preparation or notes<textarea name="note" maxLength={2000} rows={3} defaultValue={commitment === "new" ? "" : commitment.note} /></label><div className="personal-shortcuts"><button className="button button--primary" disabled={busy}>Save commitment</button>{commitment !== "new" && commitment.id && <button className="button button--ghost" type="button" disabled={busy} onClick={async () => { if (await act(`/api/personal/commitments/${commitment.id}`, undefined, "DELETE")) setCommitment(null); }}>Remove commitment</button>}</div></form></Dialog>}
    {importing && <ImportPersonal kind="calendar" act={act} busy={busy} close={() => setImporting(false)} />}
  </>;
}
