import { useEffect, useRef, useState, type ReactNode } from "react";
import { ArrowRight, Check, Pause, Play, Plus, RefreshCw, Target } from "lucide-react";
import type { AssistantProfile, PersonalProject, PersonalWorkspace, Report } from "@orchestrator/contracts";
import { PageHeader } from "./components.js";
import { Dialog } from "./alpha-pages.js";
import { AssistantSigil } from "./presence.js";
import { api } from "./lib.js";
import { MoneyPanel } from "./personal-money.js";
import { LifePanel } from "./personal-life.js";

export type PersonalAction = (path: string, body?: unknown, method?: string) => Promise<boolean>;
export type PersonalPanelProps = { data: PersonalWorkspace; act: PersonalAction; busy: boolean };
export function PersonalCard({ title, detail, children, action }: { title: string; detail?: string; children: ReactNode; action?: ReactNode }) { return <section className="personal-card"><div className="personal-card-head"><div><h2>{title}</h2>{detail && <p>{detail}</p>}</div>{action}</div>{children}</section>; }
export function PersonalMeter({ value, max, label }: { value: number; max: number; label: string }) { return <div className="personal-meter" role="meter" aria-label={label} aria-valuenow={Math.min(Math.max(value, 0), Math.max(max, 1))} aria-valuemin={0} aria-valuemax={Math.max(max, 1)}><span style={{ width: `${Math.min(100, Math.max(0, max ? value / max * 100 : 0))}%` }} /></div>; }
const errorMessage = (e: unknown) => e instanceof Error ? e.message : "Could not load your workspace";

export function PersonalAdvice({ area }: { area: "money" | "coach" | "agenda" }) {
  const [open, setOpen] = useState(false), [assistants, setAssistants] = useState<AssistantProfile[]>([]), [assistantId, setAssistantId] = useState(""), [requestId, setRequestId] = useState(() => crypto.randomUUID()), [busy, setBusy] = useState(false), [error, setError] = useState(""), [report, setReport] = useState<Report | null>(null);
  const activeRequest = useRef("");
  const labels = { money: "Ask for a money review", coach: "Reflect with a coach", agenda: "Prepare with my PA" };
  async function start() { setOpen(true); setReport(null); setError(""); const id = crypto.randomUUID(); setRequestId(id); activeRequest.current = id; try { const r = await api<{ assistants: AssistantProfile[] }>("/api/assistants"); const profiles = r.assistants.filter((a) => !a.mode || a.mode === "runtime"); setAssistants(profiles); setAssistantId(profiles.find((a) => a.templateId === ({ money: "money-guide", coach: "personal-coach", agenda: "personal-secretary" }[area]))?.id ?? profiles[0]?.id ?? ""); } catch (e) { setError(errorMessage(e)); } }
  return <><button className="button button--secondary" onClick={() => void start()}>{labels[area]}</button>{open && <Dialog title={labels[area]} close={() => { activeRequest.current = ""; setOpen(false); }}>{report ? <div className="personal-detail"><p className="eyebrow">{report.state} · saved in Reports</p><div className="personal-draft">{report.body}</div><p className="form-note">This is the assistant's response, not evidence of an external action.</p></div> : <form className="alpha-form" onSubmit={async (e) => { e.preventDefault(); const f = new FormData(e.currentTarget); setBusy(true); setError(""); try { const response = await api<Report>("/api/personal/brief", { method: "POST", body: JSON.stringify({ id: requestId, area, assistantId, question: f.get("question"), confirmed: true }) }); if (activeRequest.current === requestId) setReport(response); } catch (error) { setError(errorMessage(error)); } finally { setBusy(false); } }}><label>Assistant<select value={assistantId} required onChange={(e) => setAssistantId(e.target.value)}><option value="">Choose an assistant</option>{assistants.map((a) => <option key={a.id} value={a.id}>{a.name}</option>)}</select></label>{!assistants.length && <a href="/agents">Prepare a runtime team first</a>}<label>What would help?<textarea name="question" required maxLength={3000} rows={3} defaultValue={area === "money" ? "Explain the gaps in my money plan and a sensible educational next step." : area === "coach" ? "Help me understand what is getting in the way and choose one small step for this week." : "Prepare my next day and draft the follow-up I should consider."} /></label><p className="form-note">Shared context: {area === "money" ? "your money settings and aggregate cash-flow/allocation summary. Merchant records and individual holdings are excluded." : area === "coach" ? "up to ten active goals, their reasons and the last ten check-ins per goal." : "your next twenty open commitments, including notes."} A separate source session is requested. Isolation and read-only tools must be enforced by the runtime.</p><label className="check-label"><input type="checkbox" required /><span>I authorize sharing this context with the selected assistant and its configured provider. I have confirmed its source restrictions.</span></label>{error && <p className="form-error" role="alert">{error}</p>}<button className="button button--primary" disabled={busy || !assistantId}>{busy ? "Preparing your response…" : "Prepare my response"}</button></form>}</Dialog>}</>;
}

export function PersonalPage({ notify }: { notify(message: string, tone?: "neutral" | "success" | "error"): void }) {
  const [data, setData] = useState<PersonalWorkspace | null>(null), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  const [area, setArea] = useState(new URLSearchParams(location.search).get("area") ?? "today");
  const [month, setMonth] = useState(new Date().toISOString().slice(0, 7));
  const load = async () => { try { setData(await api<PersonalWorkspace>(area === "money" ? `/api/personal?month=${month}` : "/api/personal")); setError(""); } catch (e) { setError(errorMessage(e)); } };
  useEffect(() => { void load(); const timer = setInterval(() => void load(), 10_000); return () => clearInterval(timer); }, [area, month]);
  const act: PersonalAction = async (path, body, method = "POST") => { setBusy(true); try { await api(path, { method, ...(body === undefined ? {} : { body: JSON.stringify(body) }) }); await load(); return true; } catch (e) { notify(errorMessage(e), "error"); await load(); return false; } finally { setBusy(false); } };
  const select = (next: string) => { setArea(next); history.replaceState(null, "", `/personal?area=${next}`); };
  return <div className="personal-workspace"><PageHeader eyebrow="Your everyday team" title={area === "projects" ? "Projects" : area === "money" ? "Money" : area === "life" ? "Life & agenda" : "Today"} detail={area === "projects" ? "From an outcome to something you can use." : area === "money" ? "Understand your cash flow and investments." : area === "life" ? "Keep space for what matters to you." : "Your next steps, already gathered."} actions={<button className="icon-button" aria-label="Refresh personal workspace" onClick={() => void load()}><RefreshCw size={18} /></button>} />
    <nav className="personal-tabs" aria-label="Personal workspace">{["today", "projects", "money", "life"].map((item) => <button key={item} aria-current={area === item ? "page" : undefined} onClick={() => select(item)}>{item === "life" ? "Life & agenda" : item[0]!.toUpperCase() + item.slice(1)}</button>)}</nav>
    {error && <p className="form-error" role="alert">{error} <button onClick={() => void load()}>Retry</button></p>}
    {!data ? <p>Loading your workspace…</p> : area === "projects" ? <ProjectsPanel data={data} act={act} busy={busy} /> : area === "money" ? <MoneyPanel data={data} act={act} busy={busy} changeMonth={setMonth} /> : area === "life" ? <LifePanel data={data} act={act} busy={busy} /> : <>
      <div className="personal-intro"><AssistantSigil name="Compass" icon={0} state="ready" /><div><p className="eyebrow">Prepared from your records · dates in UTC</p><h2>{data.signals.filter((s) => s.severity === "action").length ? `${data.signals.filter((s) => s.severity === "action").length} things worth your attention.` : "A little structure. More space to move."}</h2><p>{data.signals.length ? "Start with one. Your team keeps the rest in view." : "Give us an outcome, import a statement or capture your next commitment."}</p></div></div>
      <div className="personal-stats">{[["Project stages accepted", data.projects.reduce((s, p) => s + p.tasks.filter((t) => t.state === "accepted").length, 0), "projects"], ["Drafts ready", data.projects.reduce((s, p) => s + p.tasks.filter((t) => t.state === "review").length, 0), "projects"], ["Open commitments", data.commitments.filter((c) => !c.done).length, "life"]].map(([label, value, target]) => <button key={String(label)} onClick={() => select(String(target))}><strong>{value}</strong><span>{label}</span></button>)}</div>
      <div className="personal-grid"><PersonalCard title="Next moves" detail="Local checks update while the gateway is running.">{data.signals.length ? data.signals.slice(0, 8).map((s) => <button className="personal-signal" key={s.id} onClick={() => select(s.area)}><span className={`signal-dot ${s.severity}`} /><div><strong>{s.title}</strong><p>{s.detail}</p></div><ArrowRight size={16} /></button>) : <div className="personal-empty"><Target size={28} /><h3>What would you like to move forward?</h3><p>One outcome is enough to prepare a first plan.</p><button className="button button--primary" onClick={() => select("projects")}>Start a project</button></div>}{data.signals.length > 8 && <p className="form-note">{data.signals.length - 8} more signals are available in the relevant workspace.</p>}</PersonalCard><PersonalCard title="Your weekly reflection" detail="Built from recorded progress.">{data.reflection.map((line) => <p className="reflection-line" key={line}>{line}</p>)}<div className="personal-shortcuts"><button className="button button--secondary" onClick={() => select("life")}>Check in</button><button className="button button--ghost" onClick={() => select("money")}>Review money <ArrowRight size={15} /></button></div></PersonalCard></div>
    </>}
  </div>;
}

function ProjectsPanel({ data, act, busy }: PersonalPanelProps) {
  const [adding, setAdding] = useState(false), [selected, setSelected] = useState<string | null>(null), [assistants, setAssistants] = useState<AssistantProfile[]>([]);
  useEffect(() => { api<{ assistants: AssistantProfile[] }>("/api/assistants").then((r) => setAssistants(r.assistants.filter((p) => !p.mode || p.mode === "runtime"))).catch(() => {}); }, []);
  const current = data.projects.find((p) => p.id === selected);
  return <><div className="personal-toolbar"><p>Describe the outcome. The first plan is prepared for you.</p><button className="button button--primary" onClick={() => setAdding(true)}><Plus size={16} /> New project</button></div>
    {!data.projects.length && <PersonalCard title="Start with the result you want" detail="A launch, a research question, a useful piece of software."><p className="form-note">We prepare three stages: plan, produce, review. Connect an assistant to turn that plan into draft deliverables.</p></PersonalCard>}
    <div className="personal-grid">{data.projects.map((p) => { const accepted = p.tasks.filter((t) => t.state === "accepted").length; return <button className="personal-card personal-project-card" key={p.id} onClick={() => setSelected(p.id)}><div className="personal-card-head"><AssistantSigil name={p.title} icon={p.kind === "research" ? 1 : 0} state={p.automatic ? "running" : "ready"} /><span className="eyebrow">{p.automatic ? "Preparing drafts" : accepted === p.tasks.length ? "Accepted" : "Your project"}</span></div><h2>{p.title}</h2><p>{p.objective}</p><PersonalMeter value={accepted} max={p.tasks.length} label={`${p.title} accepted stages`} /><div className="personal-card-foot"><span>{accepted}/{p.tasks.length} accepted{p.due ? ` · Due ${p.due}` : ""}</span><ArrowRight size={16} /></div></button>; })}</div>
    {adding && <Dialog title="A project worth moving forward" close={() => setAdding(false)}><form className="alpha-form" onSubmit={async (e) => { e.preventDefault(); const f = new FormData(e.currentTarget); if (await act("/api/personal/projects", { title: f.get("title"), objective: f.get("objective"), criteria: f.get("criteria"), kind: f.get("kind"), due: f.get("due") || null })) setAdding(false); }}><label>Project name<input name="title" required maxLength={120} placeholder="Launch a useful first version" /></label><label>The outcome<textarea name="objective" required maxLength={3000} rows={3} placeholder="What should exist when this succeeds?" /></label><label>Success criteria<textarea name="criteria" required maxLength={2000} rows={2} placeholder="What would convince you it is good enough?" /></label><div className="personal-form-grid"><label>Work type<select name="kind"><option value="general">General</option><option value="research">Research</option><option value="software">Software</option><option value="content">Content</option></select></label><label>Target date (optional)<input name="due" type="date" /></label></div><button className="button button--primary" disabled={busy}>Prepare my plan</button></form></Dialog>}
    {current && <ProjectDetail key={current.id} project={current} assistants={assistants} busy={busy} act={act} close={() => setSelected(null)} dispatchPaused={data.dispatchPaused} />}
  </>;
}

function ProjectDetail({ project: p, assistants, act, busy, close, dispatchPaused }: { project: PersonalProject; assistants: AssistantProfile[]; act: PersonalAction; busy: boolean; close(): void; dispatchPaused: boolean }) {
  const [assistantId, setAssistantId] = useState(p.assistantId ?? assistants.find((a) => a.templateId === "project-partner")?.id ?? assistants.find((a) => a.templateId === "coordinator")?.id ?? assistants[0]?.id ?? ""), [confirmed, setConfirmed] = useState(false), [evidence, setEvidence] = useState<Record<string, string>>({});
  const pending = p.tasks.some((t) => t.state === "running" || t.state === "unknown");
  return <Dialog title={p.title} close={close}><div className="personal-detail"><p>{p.objective}</p><details><summary>Success criteria & scope</summary><p>{p.criteria}</p><p>Three text drafting stages. Source claims are preserved; acceptance records your review, not independent verification.</p></details>
    {p.issue && <p className="form-error" role="status">{p.issue}</p>}{dispatchPaused && <p className="form-note">Global dispatch is paused. Resume it in Team before preparing drafts.</p>}
    <div className="personal-automation">{p.automatic ? <><p><Play size={14} /> Preparing one stage at a time. You can leave this screen.</p><button className="button button--secondary" disabled={busy} onClick={() => void act(`/api/personal/projects/${p.id}/automation`, { version: p.version, enabled: false, assistantId: p.assistantId })}><Pause size={15} /> Pause</button></> : p.tasks.some((t) => t.state === "queued") && !pending ? <form className="alpha-form" onSubmit={async (e) => { e.preventDefault(); if (await act(`/api/personal/projects/${p.id}/automation`, { version: p.version, enabled: true, assistantId, confirmed })) { setConfirmed(false); void act(`/api/personal/projects/${p.id}/advance`); } }}><label>Assistant<select value={assistantId} onChange={(e) => setAssistantId(e.target.value)} required><option value="">Choose an assistant</option>{assistants.map((a) => <option key={a.id} value={a.id}>{a.name}</option>)}</select></label>{!assistants.length && <p><a href="/agents">Prepare a runtime team first</a></p>}<label className="check-label"><input type="checkbox" checked={confirmed} onChange={(e) => setConfirmed(e.target.checked)} required /><span>Share this project's objective, criteria and drafts with this assistant. I have restricted its source tools to read-only work and confirmed its provider. Prepare up to three drafting turns.</span></label><button className="button button--primary" disabled={busy || dispatchPaused || !assistantId}>Prepare deliverables</button><small>Runs while the gateway is awake. Pause stops new requests; a running source request may finish.</small></form> : null}</div>
    <ol className="personal-stages">{p.tasks.map((t, i) => <li key={t.id}><div className="stage-heading"><span className="stage-number">{t.state === "accepted" ? <Check size={16} /> : i + 1}</span><div><h3>{t.title}</h3><span className="eyebrow">{t.state === "review" ? "Draft ready · source claim" : t.state}</span></div></div>{t.body && <details open={t.state === "review"}><summary>Read deliverable</summary><div className="personal-draft">{t.body}</div></details>}{!!t.history?.length && <details><summary>Previous versions ({t.history.length})</summary>{t.history.map((h, n) => <div key={n}><p className="form-note">Previously {h.state} - {h.updatedAt}</p><div className="personal-draft">{h.body || "No draft was produced."}</div>{h.evidence && <p className="personal-evidence">{h.evidence}</p>}</div>)}</details>}{t.evidence && <p className="personal-evidence">Your evidence: {t.evidence}</p>}{["review", "unknown"].includes(t.state) && <form className="alpha-form" onSubmit={async (e) => { e.preventDefault(); await act(`/api/personal/projects/${p.id}/tasks/${t.id}/review`, { version: p.version, action: t.state === "review" ? "accept" : "reconcile-result", evidence: evidence[t.id] ?? "" }); }}><label>{t.state === "unknown" ? "Source result or reconciliation evidence" : "Acceptance evidence"}<textarea required rows={2} maxLength={4000} value={evidence[t.id] ?? ""} onChange={(e) => setEvidence({ ...evidence, [t.id]: e.target.value })} placeholder={t.state === "review" ? "What did you check? Include a source or test result." : "Inspect the source, then record what happened."} /></label><div className="personal-shortcuts"><button className="button button--secondary" disabled={busy}>{t.state === "review" ? "Accept stage" : "Record source result"}</button>{t.state === "review" && <button type="button" className="button button--ghost" disabled={busy || pending || !evidence[t.id]?.trim()} onClick={() => void act(`/api/personal/projects/${p.id}/tasks/${t.id}/review`, { version: p.version, action: "revise", evidence: evidence[t.id] })}>Revise from these notes</button>}{t.state === "unknown" && <button type="button" className="button button--ghost" disabled={busy || !evidence[t.id]?.trim()} onClick={() => void act(`/api/personal/projects/${p.id}/tasks/${t.id}/review`, { version: p.version, action: "reconcile-not-sent", evidence: evidence[t.id] })}>Confirmed not sent</button>}</div></form>}</li>)}</ol>
    {!p.automatic && !pending && <button className="button button--ghost" disabled={busy} onClick={async () => { if (await act(`/api/personal/projects/${p.id}`, undefined, "DELETE")) close(); }}>Remove project from workspace</button>}
  </div></Dialog>;
}
